[Device]

stitchLatency = 10000
submitLatency = 100
stitchMaxSize = 100

submachineTypes = ["AIC", "AIV", "HUB"]

submitTopo = false
submitTopoPath = ""
replayEnable = false
replayFile = "_simulate.swim.json"
replayTaskTimeScaling = false