[Pipe]

ubSizeThreshold = 196608 # 192 * 1024 Bytes
l1SizeThreshold = 524288 # 512 * 1024 Bytes
l0aSizeThreshold = 65536 # 64 * 1024 Bytes
l0bSizeThreshold = 65536 # 64 * 1024 Bytes
l0cSizeThreshold = 131072 # 128 * 1024 Bytes